ServerEvents.recipes(event => {

    event.recipes.gtceu.autoclave("charged_certus_quartz_crystal")
        .itemInputs('4x ae2:certus_quartz_crystal')
        .inputFluids("gtceu:ruthenium 72")
        .itemOutputs("2x ae2:charged_certus_quartz_crystal")
        .duration(1200)
        .EUt(16384)
    event.recipes.gtceu.autoclave("fluix_pearl")
        .itemInputs("minecraft:ender_pearl")
        .inputFluids("gtceu:europium 72")
        .itemOutputs("ae2:fluix_pearl")
        .duration(1200)
        .EUt(16384)
    event.recipes.gtceu.autoclave("rose_quartz")
        .itemInputs("minecraft:quartz")
        .inputFluids("gtceu:redstone 72")
        .itemOutputs("create:rose_quartz")
        .duration(280)
        .EUt(GTValues.VA[GTValues.HV])
})