ServerEvents.recipes(event => {
    event.recipes.gtceu.canner("radaway_fluid")
        .itemInputs('gtceu:fluid_cell')
        .itemOutputs("nuclearcraft:radaway")
        .inputFluids(Fluid.of('nuclearcraft:radaway', 250))
        .duration(320)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(1)
    event.recipes.gtceu.canner("slow_radaway_fluid")
        .itemInputs('gtceu:fluid_cell')
        .itemOutputs("4x nuclearcraft:radaway_slow")
        .inputFluids(Fluid.of('nuclearcraft:radaway', 250))
        .duration(320)
        .EUt(GTValues.VA[GTValues.HV])
        .circuit(2)
})