StartupEvents.registry('block', event => {
    event.create('neodyte_coil_block', 'gtceu:coil')
        .temperature(3400)
        .level(8)
        .energyDiscount(24) // (1)
        .tier(4)
        .coilMaterial(() => GTMaterials.get('neodyte'))
        .texture('kubejs:block/coils/neodyte_coil_block')
        .hardness(14)
        .requiresTool(true)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .soundType("metal")
    event.create('magnesium_diboride_coil_block', 'gtceu:coil')
        .temperature(3150)
        .level(3)
        .energyDiscount(6) 
        .tier(2)
        .coilMaterial(() => GTMaterials.get('magnesium_diboride'))
        .texture('kubejs:block/magnesium_diboride_coil_block')
        .hardness(6)
        .requiresTool(true)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .soundType("metal")
})