StartupEvents.registry('block', event => {
    event.create('neodyte_coil_block', 'gtceu:coil')
        .temperature(3400)
        .level(8)
        .energyDiscount(24) // (1)
        .tier(4)
        .coilMaterial(() => GTMaterials.get('neodyte'))
        .texture('kubejs:block/coils/neodyte_coil_block')
        .hardness(14)
        .requiresTool(true)
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .soundType("metal")
    event.create('bismuth_bronze_coil_block', 'gtceu:coil')
        .temperature(2700)
        .level(3)
        .energyDiscount(8) // (1)
        .tier(2)
        .coilMaterial(() => GTMaterials.get('bismuth_bronze'))
        .texture('kubejs:block/coils/bismuth_bronze_coil_block')
        .hardness(14)
        .requiresTool(true)
        
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .soundType("metal")
    event.create('disamaruium_nickel_cobaltite_coil_block', 'gtceu:coil')
        .temperature(4800)
        .level(5)
        .energyDiscount(8) // (1)
        .tier(2)
        .coilMaterial(() => GTMaterials.get('disamaruium_nickel_cobaltite'))
        .texture('kubejs:block/coils/disamaruium_nickel_cobaltite_coil_block')
        .hardness(14)
        .requiresTool(true)
        
        .tagBlock("mineable/pickaxe")
        .tagBlock("forge:mineable/wrench")
        .soundType("metal")
})