ServerEvents.recipes(event => {
    event.recipes.gtceu.extractor("minecraft:cocoa_beans")
        .itemInputs("4x minecraft:cocoa_beans")
        .outputFluids(Fluid.of('nuclearcraft:chocolate_liquor', 144))
        .itemOutputs('nuclearcraft:cocoa_butter')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer("nuclearcraft:dark_chocolate")
        .itemInputs('minecraft:sugar')
        .inputFluids("nuclearcraft:unsweetened_chocolate 144")
        .outputFluids("nuclearcraft:dark_chocolate 144")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.mixer("nuclearcraft:milk_chocolate")
        .inputFluids("nuclearcraft:dark_chocolate 144", "minecraft:milk 144")
        .outputFluids("nuclearcraft:milk_chocolate 144")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:milk_chocolate")
        .inputFluids("nuclearcraft:milk_chocolate 144")
        .itemOutputs("nuclearcraft:milk_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:unsweetened_chocolate")
        .inputFluids("nuclearcraft:unsweetened_chocolate 144")
        .itemOutputs("nuclearcraft:unsweetened_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:dark_chocolate")
        .inputFluids("nuclearcraft:dark_chocolate 144")
        .itemOutputs("nuclearcraft:dark_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:marshmallow")
        .inputFluids("nuclearcraft:marshmallow 144")
        .itemOutputs("nuclearcraft:marshmallow")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.forming_press("nuclearcraft:smore")
        .itemInputs("3x nuclearcraft:marshmallow", "2x nuclearcraft:graham_cracker", "3x nuclearcraft:milk_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.forming_press('nuclearcraft:graham_cracker')
        .notConsumable("gtceu:ingot_casting_mold")
        .itemInputs("5x gtceu:wheat_dust")
        .itemOutputs("nuclearcraft:graham_cracker")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
})