ServerEvents.recipes(event => {
    event.recipes.gtceu.extractor("minecraft:cocoa_beans")
        .itemInputs("4x minecraft:cocoa_beans")
        .outputFluids(Fluid.of('nuclearcraft:chocolate_liquor', 144))
        .itemOutputs('nuclearcraft:cocoa_butter')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.extractor("gelatin")
        .itemInputs("minecraft:beef")
        .outputFluids(Fluid.of('nuclearcraft:gelatin', 144))
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.extractor("nuclearcraft:cocoa_butter")
        .itemInputs("nuclearcraft:cocoa_butter")
        .outputFluids(Fluid.of('nuclearcraft:cocoa_butter', 144))
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer("nuclearcraft:dark_chocolate")
        .itemInputs('minecraft:sugar')
        .inputFluids("nuclearcraft:unsweetened_chocolate 144")
        .outputFluids("nuclearcraft:dark_chocolate 144")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.mixer("nuclearcraft:milk_chocolate")
        .inputFluids("nuclearcraft:dark_chocolate 144", "minecraft:milk 144")
        .outputFluids("nuclearcraft:milk_chocolate 144")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.mixer("nuclearcraft:unsweetened_chocolate")
        .inputFluids("nuclearcraft:chocolate_liquor 144", "minecraft:water 18", 'nuclearcraft:cocoa_butter 36')
        .outputFluids("nuclearcraft:milk_chocolate 144")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:milk_chocolate")
        .inputFluids("nuclearcraft:milk_chocolate 144")
        .itemOutputs("nuclearcraft:milk_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:unsweetened_chocolate")
        .inputFluids("nuclearcraft:unsweetened_chocolate 144")
        .itemOutputs("nuclearcraft:unsweetened_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:dark_chocolate")
        .inputFluids("nuclearcraft:dark_chocolate 144")
        .itemOutputs("nuclearcraft:dark_chocolate")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.fluid_solidifier("nuclearcraft:marshmallow")
        .inputFluids("nuclearcraft:marshmallow 144")
        .itemOutputs("nuclearcraft:marshmallow")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.mixer("nuclearcraft:marshmallow")
        .inputFluids('nuclearcraft:gelatin 288', 'minecraft:water 36')
        .outputFluids("nuclearcraft:marshmallow 2881")
        .itemInputs('2x minecraft:egg', '3x minecraft:sugar', 'nuclearcraft:cocoa_butter')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.forming_press("nuclearcraft:smore")
        .itemInputs("3x nuclearcraft:marshmallow", "2x nuclearcraft:graham_cracker", "3x nuclearcraft:milk_chocolate")
        .itemOutputs("nuclearcraft:smore")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
        .circuit(2)
    event.recipes.gtceu.forming_press('nuclearcraft:graham_cracker')
        .notConsumable("gtceu:ingot_casting_mold")
        .itemInputs("5x gtceu:wheat_dust")
        .itemOutputs("nuclearcraft:graham_cracker")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.forming_press("nuclearcraft:moresmore")
        .notConsumable("gtceu:ingot_casting_mold")
        .itemInputs("4x nuclearcraft:smore", "3x nuclearcraft:marshmallow", "6x nuclearcraft:graham_cracker", "6x nuclearcraft:milk_chocolate", "4x gtceu:sugar_gem")
        .itemOutputs("nuclearcraft:moresmore")
        .duration(2400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.heat_fryer("nuclearcraft:foursmore")
        .notConsumable("gtceu:ingot_casting_mold")
        .itemInputs("8x nuclearcraft:moresmore", "7x nuclearcraft:marshmallow", "12x nuclearcraft:graham_cracker", "8x nuclearcraft:milk_chocolate", "16x gtceu:sugar_gem", "7x minecraft:honeycomb")
        .inputFluids('nuclearcraft:cocoa_butter 36')
        .itemOutputs("nuclearcraft:foursmore")
        .addData("RequiredTemp", 2350)
        .duration(3600)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.heat_fryer("nuclearcraft:evenmoresmore")
        .notConsumable("gtceu:ingot_casting_mold")
        .itemInputs("8x nuclearcraft:foursmore", "16x nuclearcraft:marshmallow", "16x nuclearcraft:graham_cracker", "12x nuclearcraft:milk_chocolate", "24x gtceu:sugar_gem", "16x minecraft:honeycomb")
        .inputFluids('kubejs:sweetener 288')
        .itemOutputs("nuclearcraft:evenmoresmore")
        .duration(3600)
        .addData("RequiredTemp", 2700)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.heat_fryer("kubejs:sweetener")
        .itemInputs("8x gtceu:sugar_gem", "16x minecraft:honeycomb", "24x minecraft:glow_berries", "32x minecraft:sweet_berries")
        .inputFluids('minecraft:milk 36')
        .outputFluids('kubejs:sweetener 1296')
        .duration(3600)
        .addData("RequiredTemp", 1200)
        .EUt(GTValues.VA[GTValues.HV])
})