ServerEvents.recipes(event => {
    event.recipes.gtceu.electrolyzer("clay_electrolyze")
        .itemInputs("16x gtceu:clay_dust")
        .itemOutputs("2x gtceu:sodium_dust")
        .itemOutputs("gtceu:lithium_dust")
        .chancedOutput("3x gtceu:aluminium_dust", 1250, 1750)
        .itemOutputs("2x gtceu:silicon_dust")
        .outputFluids(Fluid.of('minecraft:water', 6000))
        .duration(300)
        .EUt(60)
})