ServerEvents.recipes(event => {
    event.recipes.gtceu.high_temperature_turbine()
        .inputFluids(Fluid.of('minecraft:lava', 750))
        .outputFluids(Fluid.of('gtceu:earth_core_fluid_remains', 2))
        .duration(5)
        .EUt(-GTValues.VA[GTValues.LuV])
        .addData("RequiredTemp", 1000)
    event.recipes.gtceu.high_temperature_turbine()
        .inputFluids(Fluid.of('gtceu:magmatic_steam_plasma', 750))
        .outputFluids(Fluid.of('gtceu:earth_core_fluid_remains', 5))
        .duration(40)
        .EUt(-GTValues.VA[GTValues.LuV])
        .addData("RequiredTemp", 1000)
    event.recipes.gtceu.high_temperature_turbine()
        .inputFluids(Fluid.of('gtceu:high_pressure_steam_plasma', 750))
        .outputFluids(Fluid.of('gtceu:earth_core_fluid_remains', 9))
        .duration(120)
        .EUt(-GTValues.VA[GTValues.LuV])
        .addData("RequiredTemp", 1000) 
    event.recipes.gtceu.high_temperature_turbine()
        .inputFluids(Fluid.of('nuclearcraft:high_pressure_steam', 750))
        .outputFluids(Fluid.of('gtceu:distilled_water', 25))
        .duration(4)
        .EUt(-GTValues.VA[GTValues.LuV])
        .addData("RequiredTemp", 1000) 
})