StartupEvents.registry('item', event => {
    event.create('shadow_steel')
    .texture('kubejs:item/shadow_steel')
    .maxStackSize(16)
    .rarity('RARE')
    event.create('refined_radiance')
    .texture('kubejs:item/refined_radiance')
    .maxStackSize(16)
    .rarity('RARE')
})