StartupEvents.registry('item', event => {
    event.create('shadow_steel')
    .texture('kubejs:item/shadow_steel')
    .maxStackSize(16)
    .rarity('RARE')
    event.create('refined_radiance')
    .texture('kubejs:item/refined_radiance')
    .maxStackSize(16)
    .rarity('RARE')


    event.create('copper_credit')
    .texture('kubejs:item/copper_credit')
    .maxStackSize(16)
    .tooltip(Text.of("1 Credit").yellow())
    event.create('cupronickel_credit')
    .texture('kubejs:item/cupronickel_credit')
    .maxStackSize(16)
    .tooltip(Text.of("8 Credit").yellow())
    event.create('gold_credit')
    .texture('kubejs:item/gold_credit')
    .maxStackSize(16)
    .tooltip(Text.of("512 Credit").yellow())
    event.create('silver_credit')
    .texture('kubejs:item/silver_credit')
    .maxStackSize(16)
    .tooltip(Text.of("64 Credit").yellow())
    event.create('platinum_credit')
    .texture('kubejs:item/platinum_credit')
    .maxStackSize(16)
    .tooltip(Text.of("4096 Credit").yellow())
    event.create('naquadah_credit')
    .texture('kubejs:item/naquadah_credit')
    .maxStackSize(16)
    .tooltip(Text.of("32768 Credit").yellow())

})