ServerEvents.recipes(event => {
    event.recipes.gtceu.plasma_generator('gtceu:high_pressure_steam_plasma')
        .inputFluids('gtceu:high_pressure_steam_plasma 72')
        .outputFluids('gtceu:earth_core_fluid_remains 1')
        .duration(40)
        .addData("RequiredTemp", 1000)
        .EUt(-GTValues.VA[GTValues.IV])
    event.recipes.gtceu.plasma_generator('gtceu:magmatic_steam_plasma')
        .inputFluids('gtceu:magmatic_steam_plasma 144')
        .outputFluids('gtceu:earth_core_fluid_remains 3')
        .duration(120)
        .addData("RequiredTemp", 1000)
        .EUt(-GTValues.VHA[GTValues.IV])
})