JEIEvents.hideItems(event => {

    //Blackhole multiblock

    event.hide('nuclearcraft:quantum_flux_regulator')
    event.hide('nuclearcraft:chamber_port')
    event.hide('nuclearcraft:chamber_terminal')
    event.hide('nuclearcraft:event_horizon_stabilizer')
    event.hide('nuclearcraft:quantum_transformer')
    event.hide('nuclearcraft:black_hole')
    event.hide('nuclearcraft:neutronium_frame')
    event.hide('nuclearcraft:photon_concentrator')
    event.hide('nuclearcraft:particle_beam')

    //Accelerator

    event.hide('nuclearcraft:accelerator_beam_port')
    event.hide('nuclearcraft:accelerator_port')
    event.hide('nuclearcraft:accelerator_casing')
    event.hide('nuclearcraft:linear_accelerator_controller')
    event.hide("nuclearcraft:accelerator_casing_glass")
    event.hide('nuclearcraft:electromagnet_yoke')
    event.hide('nuclearcraft:accelerator_ion_source_port')
    event.hide(/nuclearcraft:.*_cooler/)


    //Target Chamber

    event.hide('nuclearcraft:target_chamber_port')
    event.hide('nuclearcraft:silicon_tracker')
    event.hide('nuclearcraft:em_calorimeter')
    event.hide('nuclearcraft:hadron_calorimeter')
    event.hide('nuclearcraft:bubble_chamber')
    event.hide('nuclearcraft:target_chamber_casing')
    event.hide('nuclearcraft:target_chamber_beam_port')
    event.hide('nuclearcraft:target_chamber_casing_glass')
    event.hide('nuclearcraft:target_chamber_camera')
    event.hide('nuclearcraft:target_chamber_controller')
    event.hide('nuclearcraft:wire_chamber')
    event.hide('nuclearcraft:ring_accelerator_controller')

    //Misc

    event.hide('nuclearcraft:target_chamber_controller')
    event.hide('nuclearcraft:positronium')
    event.hide('nuclearcraft:antihelium3')
    event.hide('nuclearcraft:source_iridium_192')
    event.hide('nuclearcraft:antihelium')
    event.hide('nuclearcraft:tungsten_filament')
    event.hide('nuclearcraft:antihydrogen')
    event.hide('nuclearcraft:antitritium')
    event.hide('nuclearcraft:glueballs')
    event.hide('nuclearcraft:tauonium')
    event.hide('nuclearcraft:antideuterium')
    event.hide('nuclearcraft:empty')
    event.hide('nuclearcraft:source_calcium_48')
    event.hide('nuclearcraft:salt')

    //Machines 

    event.hide('nuclearcraft:rock_crusher')
    event.hide('nuclearcraft:decay_hastener')
    event.hide('nuclearcraft:irradiator')
    event.hide('nuclearcraft:nuclear_furnace')
    event.hide('nuclearcraft:extractor')
    event.hide('nuclearcraft:electrolyzer')
    event.hide('nuclearcraft:pressurizer')
    event.hide('nuclearcraft:alloy_smelter')
    event.hide('nuclearcraft:melter')
    event.hide('nuclearcraft:analyzer')
    event.hide('nuclearcraft:ingot_former')
    event.hide('nuclearcraft:pump')
    event.hide('nuclearcraft:fuel_reprocessor')
    event.hide('nuclearcraft:leacher')
    event.hide('nuclearcraft:crystallizer')
    event.hide('nuclearcraft:assembler')
    event.hide('nuclearcraft:steam_turbine')
    event.hide('nuclearcraft:supercooler')
    event.hide('nuclearcraft:subatomic_liquifier')
    event.hide('nuclearcraft:centrifuge')
    event.hide('nuclearcraft:chemical_reactor')
    event.hide('nuclearcraft:fluid_infuser')
    event.hide('nuclearcraft:isotope_separator')
    event.hide('nuclearcraft:fluid_enricher')
    event.hide('nuclearcraft:gas_scrubber')
    event.hide('nuclearcraft:manufactory')
    event.hide('nuclearcraft:multiblock_builder')
    event.hide('nuclearcraft:expl')


    //Ores

    event.hide('nuclearcraft:magnesium_deepslate_ore')
    event.hide('nuclearcraft:redstone_dimmer')
    event.hide('nuclearcraft:thorium_deepslate_ore')
    event.hide('nuclearcraft:uranium_deepslate_ore')
    event.hide('nuclearcraft:magnesium_ore')
    event.hide('nuclearcraft:boron_deepslate_ore')
    event.hide('nuclearcraft:cobalt_ore')
    event.hide('nuclearcraft:platinum_deepslate_ore')
    event.hide('nuclearcraft:silver_deepslate_ore')
    event.hide('nuclearcraft:lead_ore')
    event.hide('nuclearcraft:lithium_ore')
    event.hide('nuclearcraft:thorium_ore')
    event.hide('nuclearcraft:tin_ore')
    event.hide('nuclearcraft:cobalt_deepslate_ore')
    event.hide('nuclearcraft:silver_ore')
    event.hide('nuclearcraft:uranium_ore')
    event.hide('nuclearcraft:zinc_ore')
    event.hide('nuclearcraft:boron_ore')
    event.hide('nuclearcraft:lithium_deepslate_ore')

    //Metal Storage Blocks

    event.hide('nuclearcraft:steel_block')
    event.hide('nuclearcraft:electrum_block')
    event.hide('nuclearcraft:supercold_ice_block')
    event.hide('nuclearcraft:magnesium_block')
    event.hide('nuclearcraft:cobalt_block')
    event.hide('nuclearcraft:aluminum_block')
    event.hide('nuclearcraft:platinum_block')
    event.hide('nuclearcraft:americium241_block')
    event.hide('nuclearcraft:lithium_block')
    event.hide('nuclearcraft:tin_block')
    event.hide('nuclearcraft:thorium_block')
    event.hide('nuclearcraft:californium250_block')
    event.hide('nuclearcraft:bronze_block')
    event.hide('nuclearcraft:lead_block')
    event.hide('nuclearcraft:advanced_barrel')
    event.hide('nuclearcraft:zirconium_block')
    event.hide('nuclearcraft:zinc_block')
    event.hide('nuclearcraft:boron_block')
    event.hide('nuclearcraft:uranium_block')
    event.hide('nuclearcraft:plutonium238_block')
    event.hide('nuclearcraft:uranium238_block')
    event.hide('nuclearcraft:silver_block')

    //Storage

    event.hide('nuclearcraft:elite_storage_container')
    event.hide('nuclearcraft:basic_barrel')
    event.hide('nuclearcraft:elite_barrel')
    event.hide('nuclearcraft:du_barrel')
    event.hide('nuclearcraft:advanced_barrel')
    event.hide('nuclearcraft:du_storage_container')
    event.hide('nuclearcraft:advanced_storage_container')
    event.hide('nuclearcraft:basic_storage_container')

    //Crafting Items

    event.hide('nuclearcraft:motor')
    event.hide('nuclearcraft:plate_basic')
    event.hide('nuclearcraft:silicon_boule')
    event.hide('nuclearcraft:empty_frame')
    event.hide('nuclearcraft:empty_detector')
    event.hide('nuclearcraft:coil_copper')
    event.hide('nuclearcraft:scintillator_pwo')
    event.hide('nuclearcraft:silicon_n_doped')
    event.hide('nuclearcraft:laser_assembly')
    event.hide('nuclearcraft:wire_chamber_casing')
    event.hide('nuclearcraft:advanced_processor')
    event.hide('nuclearcraft:actuator')
    event.hide('nuclearcraft:coil_magnesium_diboride')
    event.hide('nuclearcraft:steel_frame')
    event.hide('nuclearcraft:basic_electric_circuit')
    event.hide('nuclearcraft:empty_sink')
    event.hide('nuclearcraft:scintillator_plastic')
    event.hide('nuclearcraft:servo')
    event.hide('nuclearcraft:silicon_p_doped')
    event.hide('nuclearcraft:plate_elite')
    event.hide('nuclearcraft:plate_du')
    event.hide('nuclearcraft:coil_bscco')
    event.hide('nuclearcraft:silicon_wafer')
    event.hide('nuclearcraft:chassis')
    event.hide('nuclearcraft:plate_advanced')
    event.hide('nuclearcraft:plate_extreme')
    event.hide('nuclearcraft:research_paper')
    event.hide('nuclearcraft:basic_processor')
    event.hide('nuclearcraft:sic_fiber')
    event.hide('nuclearcraft:bioplastic')
    event.hide('nuclearcraft:elite_processor')
    event.hide('nuclearcraft:wire_gold_tungsten')
    event.hide('nuclearcraft:compact_nitrogen_collector')
    event.hide('nuclearcraft:nitrogen_collector')
    event.hide('nuclearcraft:upgrade_energy')
    event.hide('nuclearcraft:lava_collector')
    event.hide('nuclearcraft:compact_water_collector')
    event.hide('nuclearcraft:dense_nitrogen_collector')
    event.hide('nuclearcraft:dense_water_collector')
    event.hide('nuclearcraft:compact_helium_collector')
    event.hide('nuclearcraft:upgrade_speed')
    event.hide('nuclearcraft:sawdust')
    event.hide('nuclearcraft:flour')
    event.hide('nuclearcraft:upgrade_stack')
    event.hide('nuclearcraft:helium_collector')
    event.hide('nuclearcraft:dense_helium_collector')
    event.hide('nuclearcraft:water_collector')
    event.hide('nuclearcraft:dominos')
    event.hide('nuclearcraft:gelatin')

    //Materials

    event.hide(/nuclearcraft:.*_ingot/)
    event.hide(/nuclearcraft:.*_chunk/)
    event.hide(/nuclearcraft:.*_dust/)
    event.hide(/nuclearcraft:.*_nugget/)
    event.hide(/nuclearcraft:.*_plate/)
    event.hide(/nuclearcraft:.*_bucket/)
    event.hide(/nuclearcraft:.*_plate/)
    event.hide(/nuclearcraft:turbine_.*/)
    event.hide(/nuclearcraft:particle.*/)
})