ServerEvents.recipes(event => {
    event.recipes.gtceu.laser_engraver('ae2:printed_calculation_processor')
        .itemInputs('4x gtceu:blue_topaz_gem')
        .notConsumable("#forge:lenses/black")
        .itemOutputs('ae2:printed_calculation_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1200)
        .EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.laser_engraver('ae2:printed_logic_processor')
        .itemInputs('4x gtceu:topaz_gem')
        .notConsumable("#forge:lenses/black")
        .itemOutputs('ae2:printed_logic_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1200)
        .EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.laser_engraver('ae2:printed_engineering_processor')
        .itemInputs('4x gtceu:sapphire_gem')
        .notConsumable("#forge:lenses/black")
        .itemOutputs('ae2:printed_engineering_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(1200)
        .EUt(GTValues.VA[GTValues.IV])
})