ServerEvents.recipes(event => {
    event.recipes.gtceu.heat_fryer("create:chocolate_glazed_berries")
        .itemInputs("2x gtceu:sugar_gem",  "32x minecraft:sweet_berries")
        .inputFluids('nuclearcraft:dark_chocolate 1926')
        .itemOutputs("32x create:chocolate_glazed_berries")
        .duration(3600)
        .addData("RequiredTemp", 3200)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.heat_fryer("create:honeyed_apple")
        .itemInputs("2x minecraft:honeycomb",  "4x minecraft:apple")
        .itemOutputs('4x create:honeyed_apple')
        .duration(3600)
        .addData("RequiredTemp", 2500)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.heat_fryer("create:sweet_roll")
        .itemInputs("gtceu:sugar_gem",  "4x minecraft:bread")
        .inputFluids("minecraft:milk 1296")
        .itemOutputs('4x create:sweet_roll')
        .duration(2400)
        .addData("RequiredTemp", 2900)
        .EUt(GTValues.VA[GTValues.HV])
})