ServerEvents.recipes(event => {
    event.recipes.gtceu.electrolyzer("clay_electrolyze")
        .itemInputs("16x gtceu:clay_dust")
        .itemOutputs("2x gtceu:sodium_dust")
        .itemOutputs("gtceu:lithium_dust")
        .chancedOutput("3x gtceu:aluminium_dust", 1250, 1750)
        .itemOutputs("2x gtceu:silicon_dust")
        .outputFluids(Fluid.of('minecraft:water', 6000))
        .duration(300)
        .EUt(60)

    event.recipes.gtceu.electrolyzer("chromite_dust_electrolyze")
        .itemInputs("7x gtceu:chromite_dust")
        .itemOutputs("gtceu:iron_dust")
        .itemOutputs("2x gtceu:chromium_dust")
        .outputFluids(Fluid.of('gtceu:oxygen', 4000))
        .duration(460)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.electrolyzer("ruby_dust_electrolyze")
        .itemInputs("6x gtceu:ruby_dust")
        .itemOutputs("2x gtceu:aluminium_dust")
        .itemOutputs("gtceu:chromium_dust")
        .outputFluids(Fluid.of('gtceu:oxygen', 3000))
        .duration(460)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.electrolyzer("uvarovite_dust_electrolyze")
        .itemInputs("20x gtceu:uvarovite_dust")
        .itemOutputs("3x gtceu:silicon_dust")
        .itemOutputs("3x gtceu:calcium_dust")
        .itemOutputs("2x gtceu:chromium_dust")
        .outputFluids(Fluid.of('gtceu:oxygen', 12000))
        .duration(960)
        .EUt(GTValues.VA[GTValues.EV])
})